services:
  stock-back:
    container_name: stock-back
    build: .
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/app/certs
    environment:
      - spring.datasource.url=jdbc:mysql://stock-database:3306/stock_db
      - spring.datasource.username=stock
      - spring.datasource.password=StockBackend@2024ml
      - JAVA_TOOL_OPTIONS=-Xss200K
    depends_on:
      - mysql_db
    networks:
      - stock-network

  mysql_db:
    image: mysql:8.0
    container_name: stock-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: StockBackend@2024ml
      MYSQL_DATABASE: stock_db
      MYSQL_USER: stock
      MYSQL_PASSWORD: StockBackend@2024ml
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stock-network

volumes:
  mysql-data:

networks:
  stock-network:
    driver: bridge